# Generated by Django 4.2.4 on 2024-07-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_patientdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patientdata',
        ),
    ]
