# Generated by Django 4.2.4 on 2024-07-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_patientdata_address_alter_patientdata_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdata',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
    ]
