# Generated by Django 4.2.4 on 2024-07-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_appointmentdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdata',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
